# Funding for JobPrep
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [aliammari1]
custom: ["https://buymeacoffee.com/aliammari"]
