import {
  Loader2,
  Mail,
  Github,
  Chrome,
  Check,
  AlertCircle,
  Info,
  ArrowLeft,
  Eye,
  EyeOff,
  Shield,
  Key,
  User,
  Settings,
  LogOut,
  Bell,
  Building,
  Users,
  QrCode,
  Smartphone,
  Copy,
  Download,
  Link as LinkIcon,
  Unlink,
  Fingerprint,
  Plus,
  Trash2,
  MoreVertical,
  UserPlus,
  UserMinus,
  Crown,
  Ban,
  UserCheck,
  Send,
  Activity,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  gitHub: Github,
  github: Github,
  google: Chrome,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  arrowLeft: ArrowLeft,
  eye: Eye,
  eyeOff: EyeOff,
  shield: Shield,
  key: Key,
  user: User,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  building: Building,
  users: Users,
  qrCode: QrCode,
  smartphone: Smartphone,
  copy: Copy,
  download: Download,
  link: LinkIcon,
  unlink: Unlink,
  fingerprint: Fingerprint,
  plus: Plus,
  trash: Trash2,
  moreVertical: MoreVertical,
  userPlus: UserPlus,
  userMinus: UserMinus,
  crown: Crown,
  ban: Ban,
  userCheck: UserCheck,
  send: Send,
  activity: Activity,
} as const;
